// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtOcF7Fdi0jD2DNLPff1HJGqsTpmQo49s',
    appId: '1:614900830669:web:21262f0fabedb566f3f484',
    messagingSenderId: '614900830669',
    projectId: 'th-buoi2-26c01',
    authDomain: 'th-buoi2-26c01.firebaseapp.com',
    storageBucket: 'th-buoi2-26c01.firebasestorage.app',
    measurementId: 'G-BC9LTJ1RY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiy5mqKonh-nXtCyqTJJ-P-FREHWy99cM',
    appId: '1:614900830669:android:e0ec98107af754dff3f484',
    messagingSenderId: '614900830669',
    projectId: 'th-buoi2-26c01',
    storageBucket: 'th-buoi2-26c01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtLCvKhSIsXNv6VH-kpR3Q7KxdrU_l_iE',
    appId: '1:614900830669:ios:9056126c5303cf8ef3f484',
    messagingSenderId: '614900830669',
    projectId: 'th-buoi2-26c01',
    storageBucket: 'th-buoi2-26c01.firebasestorage.app',
    iosBundleId: 'com.example.th3Lab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtLCvKhSIsXNv6VH-kpR3Q7KxdrU_l_iE',
    appId: '1:614900830669:ios:9056126c5303cf8ef3f484',
    messagingSenderId: '614900830669',
    projectId: 'th-buoi2-26c01',
    storageBucket: 'th-buoi2-26c01.firebasestorage.app',
    iosBundleId: 'com.example.th3Lab3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtOcF7Fdi0jD2DNLPff1HJGqsTpmQo49s',
    appId: '1:614900830669:web:d67e51b74d1e3010f3f484',
    messagingSenderId: '614900830669',
    projectId: 'th-buoi2-26c01',
    authDomain: 'th-buoi2-26c01.firebaseapp.com',
    storageBucket: 'th-buoi2-26c01.firebasestorage.app',
    measurementId: 'G-JMHP3Z1WH9',
  );
}
